name: opcua_ffi
description: Bindings to locka99/opcua
version: 0.0.1-DEV
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  lints: ^2.0.1
  freezed_annotation: ^2.2.0
  flutter_rust_bridge: ^2.5.0
  flutter_rust_bridge_utils:
    path: frb_utils
dev_dependencies:
  test: ^1.21.4
  freezed: ^2.1.0+1
  build_runner: ^2.4.4
  ffigen: ^11.0.0
